# Generated by Django 5.0.7 on 2026-07-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id_charge', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('montant', models.FloatField()),
            ],
        ),
    ]
