# Generated by Django 5.0.7 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('matiere_personnalise', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_renumeration', models.FloatField()),
                ('statut_paiement', models.CharField(max_length=50)),
                ('statut_affectation', models.CharField(max_length=50)),
                ('heures_restantes', models.FloatField()),
                ('a_ete_renouvelee', models.BooleanField(default=False)),
                ('recu', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
