# Generated by Django 5.0.7 on 2026-07-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0001_initial'),
        ('forfaits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='forfait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='forfaits.forfait'),
        ),
    ]
