# Generated by Django 5.0.7 on 2026-07-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0002_initial'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='rh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='rh.rh'),
        ),
    ]
