# Generated by Django 5.0.7 on 2026-08-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0005_alter_affectation_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='matiere',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='statut_affectation',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
