# Generated by Django 5.0.7 on 2026-08-17 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0006_alter_affectation_matiere_and_more'),
        ('enseignants', '0006_alter_enseignant_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='enseignants.enseignant'),
        ),
    ]
