# Generated by Django 5.0.7 on 2026-07-16 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField()),
                ('type_client', models.CharField(choices=[('parent', 'Parent'), ('etudiant', 'Étudiant')], default='parent', help_text='Permet de distinguer si le client est un parent ou un étudiant indépendant', max_length=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
