# Generated by Django 5.0.7 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id_experience', models.AutoField(primary_key=True, serialize=False)),
                ('intitule_poste', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_finale', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
