# Generated by Django 5.0.7 on 2026-07-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affectations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('duree', models.CharField(max_length=50)),
                ('qualite', models.CharField(blank=True, max_length=100, null=True)),
                ('type_seance', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('prevue', 'Prévue'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='prevue', max_length=20)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='affectations.affectation')),
            ],
        ),
    ]
