# Generated by Django 5.0.7 on 2026-08-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('date_envoi_prevue', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_attente', max_length=15)),
                ('date_envoi_reelle', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True, default='')),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rappel', to='seances.seance')),
            ],
            options={
                'indexes': [models.Index(fields=['statut', 'date_envoi_prevue'], name='seances_rap_statut_133910_idx')],
            },
        ),
    ]
