# Generated by Django 5.0.7 on 2026-07-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes_bancaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePaiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('montant', models.FloatField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('paye', 'Payé')], default='en_attente', max_length=20)),
                ('recu_paiement', models.CharField(blank=True, max_length=255, null=True)),
                ('raison', models.CharField(blank=True, max_length=255, null=True)),
                ('type_demande', models.CharField(max_length=100)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='comptes_bancaires.comptebancaire')),
            ],
        ),
    ]
