# Generated by Django 5.0.7 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heureA', models.IntegerField()),
                ('type', models.CharField(choices=[('horaire', 'Horaire'), ('forfait', 'Forfait')], max_length=20)),
                ('nombre_heure', models.IntegerField()),
                ('prix', models.FloatField()),
                ('seuil', models.IntegerField()),
            ],
        ),
    ]
