# Generated by Django 5.0.13 on 2026-08-01 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuilles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portefeuille',
            options={'verbose_name': 'Portefeuille', 'verbose_name_plural': 'Portefeuilles'},
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='devise',
            field=models.CharField(default='MAD', max_length=3),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuilles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECHARGE', 'Recharge'), ('PAIEMENT', 'Paiement'), ('REMBOURSEMENT', 'Remboursement'), ('ANNULATION', 'Annulation')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('methode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('COMPLETE', 'Complété'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portefeuilles.portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
