# Generated by Django 5.0.7 on 2026-07-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneDeplacement',
            fields=[
                ('id_zone_Deplacement', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneDeplacementEnseignant',
            fields=[
                ('id_zone_deplacement', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_deplacement', to='utilisateurs.utilisateur')),
                ('zone_deplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='zones_deplacement.zonedeplacement')),
            ],
        ),
    ]
