# Generated by Django 5.0.7 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_banque', models.CharField(max_length=20)),
                ('code_ville', models.CharField(max_length=20)),
                ('numero_compte', models.CharField(max_length=50)),
                ('cle_rib', models.CharField(max_length=10)),
                ('nom_banque', models.CharField(max_length=100)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
    ]
