# Generated by Django 5.0.7 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id_diplome', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('specialite', models.CharField(max_length=150)),
                ('date_obtention', models.DateField()),
            ],
        ),
    ]
