# Generated by Django 5.0.7 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_envoi', models.DateField(auto_now_add=True)),
                ('lecture', models.BooleanField(default=False)),
            ],
        ),
    ]
