# Generated by Django 5.0.7 on 2026-08-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0003_enseignant_diplome_enseignant_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='matiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
