# Generated by Django 5.0.7 on 2026-08-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0004_enseignant_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='tarif_heure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
