# Generated by Django 5.0.7 on 2026-08-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0005_enseignant_disponible_enseignant_tarif_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matiere',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
