# Generated by Django 5.0.7 on 2026-07-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('niveau', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=100)),
                ('nom_parent', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('etablissement', models.CharField(max_length=150)),
                ('matricule', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='clients.client')),
            ],
        ),
    ]
